### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by Neppord** [nathan7/level-promise#1]
Even if the project is simple there realy should be some tests to show how the lib works and that it works.

**Comment by edef1c** [comment]
I'm using this library in real projects, and it works just fine thus far.
Tests are welcome, but I'm not likely to write any myself.

**Comment by Neppord** [comment]
Do you have a testing lib you prefer @nathan7?

**Comment by edef1c** [comment]
My preferred testing combo happens to be Mocha + Chai + Sinon — a job well done!
