### ISSUE TITLE
Does it work with `createReadStream` method?

### ISSUE THREAD

**Issue by tnguyen14** [nathan7/level-promise#6]
Hi, I'm looking into using this library and was wondering if this library promisify the `createReadStream` method?

**Comment by edef1c** [comment]
Nope, that method is just passed through directly. Working as intended.

**Comment by tnguyen14** [comment]
Thanks for the answer. That was my suspicion as well, but I wasn't sure. Would be great if the doc could mentioned what methods are passed through that way? I tried looking into the source code but it wasn't outlined there either, as this works at a lower level that I was not familiar with.

**Comment by edef1c** [comment]
It uses [level-manifest](https://github.com/dominictarr/level-manifest) and wraps all the methods specified as `async`, and passes the rest through. `createReadStream`'s type in the manifest is `readable`, so it is passed through.
